name: manual

on:
  workflow_dispatch:
    inputs:
      part:
        description: "Semver part to bump (major, minor, patch)"
        type: choice
        required: true
        default: "patch"
        options: ["major", "minor", "patch"]

jobs:
  try-me:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure git for github-actions[bot]
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install commitizen
        run: pip install commitizen
      - name: Bump version with commitizen
        run: |
          cz bump --increment ${{ github.event.inputs.part }}
      - name: Commit and push with tags
        run: git push --follow-tags
    #       git add .
    #       git commit -m "Bump version"
