name: Setup workflow environment

on:
  workflow_call:
    inputs:
      python-version:
        description: "Python version"
        type: string
        required: false
        default: "3.11"
      os:
        description: "Operating system"
        type: string
        required: false
        default: "ubuntu-latest"
      install-dependencies:
        description: "Whether to install dependencies"
        type: boolean
        required: false
        default: false

jobs:
  setup:
    name: Setup GitHub actions environment
    runs-on: ${{ inputs.os }}

    steps:
      - name: Get repo
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
      - name: Install dependencies
        if: ${{ inputs.install-dependencies }}
        run: poetry install --with dev
